### ISSUE TITLE
Fix design of members carousel

### ISSUE THREAD

**Issue by SuelaCark** [AUBGTheHUB/monolith#320]
Basically what we are aiming at is to change the design structure of the members carousel. By that I mean that we need to find a way to  make all members easily visible in the carousel because with the current structure, noone will scroll till the end of the carousel.  Hence, the members last on the carousel will not even be viewed at all.

What I suggested is to reuse the same carousel multiple time to create distinction between departments. The structure of all carousels will be as follows:
(Carousel 1) HUB Board - President, 2 VPs, Treasurer, Head of Departments
(Carousel 2) Design and Marketing members 
(Carousel 3) Dev members
(Carousel 4) Logistics members
(Carousel 5) PR members

If you have any other design structure suggestions, feel free to share them below.

**Comment by asynchroza** [comment]
> Actually what I said above is the less-efficient but easier way to implement this. However, we thought of another more efficient idea. We thought of making a few side buttons with the name of each respective department and implementing a function which will filter the images and show them by department.
> 
> I am asking about the design and its implementation since we will have to add all pictures of the members in the admin panel in a hierarchical way.
> 
> @asynchroza do you think that the dev.thehub-aubg.com will, as of now, be able to hold all the pictures? Also, do we need to compress the pictures before adding them?

* Images are not stored on the server. We have an AWS S3 object storage which hosts the image files and the browsers make a request towards it in order to fetch the corresponding members images and store them in their cache. 

* Your idea is achievable. You may add 4 buttons which fetch and rebuild the [array](https://github.com/AUBGTheHUB/spa-website-2022/blob/3672368d988b5dea8289ce4018e7eff9ea37e24e/packages/web/src/components/spa/MembersSection/MembersSection.jsx#L10) which holds the cards. A problem which might arise is the transition being too harsh. One way to approach this is to come up with some solution which would fade out and fade in the component whenever a button is clicked. I don't think this will be a lot of work but it takes time to fine-tune such animations.

* [I forked the carousel library](https://github.com/AUBGTheHUB/react-hovering-cards-carousel), so if you decide you can implement something which will help fix some of these issues, open a PR towards the main repo and I will deploy a new version.

**Comment by SuelaCark** [comment]
Since we will not be working on the above-mentioned^^ I think we should still fix a few things for the members section. 
(1) Make member's card text a little smaller and make sure that there is space (margin left and right) within the container onHover
(2) In a few laptops, the arrows exceed the width of the page and are cropped in half.
