### ISSUE TITLE
[STORY] Finalize workflow for hackathon registration

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#480]
## Brief description:
![367917124_324376909964938_6828015485581530710_n (1)](https://github.com/AUBGTheHUB/monolith/assets/38375079/160c82c1-6849-42c2-9018-ea6ff8e8c184)

## How to achieve it:
Follow the schema

**Comment by asynchroza** [comment]
First of all, this schema is not clear enough - barely readable, lacks clarity and it's misleading in terms of overall workflow.
I suggest that you and @Aleks1908 use https://excalidraw.com next time.

* Availability of registration form is checked on initial load, not after picking an _option_ on the UI. Here, you need to talk to PR and decide whether you will be closing the registration once the team capacity is being reached or you will allow participants without teams to keep registering. Consider all cases and discuss whether we have to come up with some algorithm for creating new teams for allocating participants without teams so that we don't reach a point where we need to put participants in predefined teams. I bet most people won't like having some random person in their team when they've explicitly signed up with friends (@nikolayninov @SamuilMladenov your input is required here). In terms of technical execution, this check is not a separate endpoint. Why? Because we already have a feature switch for the registration platform so instead of making countless requests towards the API, we just switch the flag within the DB. This would mean using the upsert function of the `feature_switches_controller` which is called as a coroutine at the end if capacity is reached. This is why you need clearly defined architecture when it comes to such a complex story. 
*  When creating a team, the creator of the admin receives two emails - for verifying their identity and once verified, an email with the sharable url of the team. How do you intend on handling that? What url is used for verifying the identity? I don't see it defined. Do verification urls lead to a page which has a button which would then make a request to the API to notify it that the user has been verified? A lot of email clients open urls beforehand to check whether they're malicious - this means we might get a lot of false positives if we don't implement a button.
* I mentioned to @Aleks1908 that new team members will be registering using the same registration form but with some more additional logic baked in. You should figure out how to filter out the team. Do you pass the unique_id of the team used from the url in the body request? Is it a query parameter or a path parameter?
* Additionally, the registration form loaded from the team url should check whether there are any free spots left the team on first load, not after the user has submitted their details.
* No new pages should be used at all! All verifications and messages should be either handled as modals or [notifications](https://react-hot-toast.com). 

![](https://assets-global.website-files.com/5c7fdbdd4e3feeee8dd96dd2/5e28b7569ec279665ff7908d_zapier%20teams.gif)

^ **This took me 1 minute to figure out and a couple more to write. This story needs more work.**

**Comment by nikolayninov** [comment]
I have one additional idea, coming either from the tues' or sofia university's hackathon page. They displayed the registered teams on their website. Maybe we can add this(+ display the number of ppl without a team) so that participants without a team can decide whether it's worth it to register or not.

**Comment by nikolayninov** [comment]
Regarding when should the registration form be closed, this issue still has to be discussed, but i'd suggest for example:
let's say we have 12 teams cap
11 predefined teams
1 team out of ppl without a team
Another option (the one i think is best for everyone) is not to allow ppl to register without a team but rather display the already registered ones and singletons can contact them on their own and ask to join, this way we can utilize the url functionality even better 🫡

Of course, in case someone decides to register alone as a team in case he finds more ppl and wants to save a spot, we can add smth like "if you don't have 4 ppl in your team 1 week prior to the hackathon, your team will be disqualified and your spot will be empty lol"

**Comment by asynchroza** [comment]
> I have one additional idea, coming either from the tues' or sofia university's hackathon page. They displayed the registered teams on their website. Maybe we can add this(+ display the number of ppl without a team) so that participants without a team can decide whether it's worth it to register or not.

Can you provide links for safekeeping? I do like the idea of having the teams displayed and the total amount of people. It will look even cooler if we somehow gamify it and have them show as if it's a game dashboard.

**Comment by asynchroza** [comment]
> Regarding when should the registration form be closed, this issue still has to be discussed, but i'd suggest for example:
> let's say we have 12 teams cap
> 11 predefined teams
> 1 team out of ppl without a team
> Another option (the one i think is best for everyone) is not to allow ppl to register without a team but rather display the already registered ones and singletons can contact them on their own and ask to join, this way we can utilize the url functionality even better 🫡
> 
> Of course, in case someone decides to register alone as a team in case he finds more ppl and wants to save a spot, we can add smth like "if you don't have 4 ppl in your team 1 week prior to the hackathon, your team will be disqualified and your spot will be empty lol"

What do you think about my suggestion from the comment - automatically allocating teams for participants without teams?
Have a new team form up for each 6 non-team participants. 

For example: 
There are 6 regular teams.
6 non-team participants have signed up. These 6 members fill up the capacity but do not exceed it. Therefore one team for non-team participants is enough. Total teams - 7

A new non-team participant tries to sign up. Now we have 7 non-team participants. A new team is being created because the count with the new participant will exceed 6 (max cap of team members). Therefore this new participant is being allocated to the new team. Total teams - 8

We can further extend this by splitting the non-team participants equally among the teams. Have the two non-team teams as 4 and 3 participants instead of 6 and 1. Nevertheless, I think this will increase the complexity quite a bit and we can do this manually on the day of the hackathon.

**Comment by nikolayninov** [comment]
> > I have one additional idea, coming either from the tues' or sofia university's hackathon page. They displayed the registered teams on their website. Maybe we can add this(+ display the number of ppl without a team) so that participants without a team can decide whether it's worth it to register or not.
> 
> Can you provide links for safekeeping? I do like the idea of having the teams displayed and the total amount of people. It will look even cooler if we somehow gamify it and have them show as if it's a game dashboard. 

Ahah i like the gamification idea.

Here's the link:
https://hacktues.bg/teams

**Comment by asynchroza** [comment]
> Regarding when should the registration form be closed, this issue still has to be discussed, but i'd suggest for example:
> let's say we have 12 teams cap
> 11 predefined teams
> 1 team out of ppl without a team
> Another option (the one i think is best for everyone) is not to allow ppl to register without a team but rather display the already registered ones and singletons can contact them on their own and ask to join, this way we can utilize the url functionality even better 🫡
> 
> Of course, in case someone decides to register alone as a team in case he finds more ppl and wants to save a spot, we can add smth like "if you don't have 4 ppl in your team 1 week prior to the hackathon, your team will be disqualified and your spot will be empty lol"

Now, I better grasp what you mean by saying "better utilize the url functionality". That's a cool idea I would like to explore but this will require the implementation of an approval functionality for team admins to accept members within the teams. Additionally, this way we depend too much on having people read our guide on how to sign up when we can have most of the stuff abstracted and just do it behind the scenes. We're not allowed to share any public info about the teams other than name and capacity (at least that's what I assume).

**Comment by nikolayninov** [comment]
> > Regarding when should the registration form be closed, this issue still has to be discussed, but i'd suggest for example:
> > let's say we have 12 teams cap
> > 11 predefined teams
> > 1 team out of ppl without a team
> > Another option (the one i think is best for everyone) is not to allow ppl to register without a team but rather display the already registered ones and singletons can contact them on their own and ask to join, this way we can utilize the url functionality even better 🫡
> > 
> > Of course, in case someone decides to register alone as a team in case he finds more ppl and wants to save a spot, we can add smth like "if you don't have 4 ppl in your team 1 week prior to the hackathon, your team will be disqualified and your spot will be empty lol"
> 
> What do you think about my suggestion from the comment - automatically allocating teams for participants without teams?
> Have a new team form up for each 6 non-team participants. 
> 
> For example: 
> There are 6 regular teams.
> 6 non-team participants have signed up. These 6 members fill up the capacity but do not exceed it. Therefore one team for non-team participants is enough. Total teams - 7
> 
> A new non-team participant tries to sign up. Now we have 7 non-team participants. A new team is being created because the count with the new participant will exceed 6 (max cap of team members). Therefore this new participant is being allocated to the new team. Total teams - 8
> 
> We can further extend this by splitting the non-team participants equally among the teams. Have the two non-team teams as 4 and 3 participants instead of 6 and 1. Nevertheless, I think this will increase the complexity quite a bit and we can do this manually on the day of the hackathon.
> 


I think this might create weirdly balanced teams, e.g. all designers, all coders, etc. (Iren's sister's team from last year is a good example of that) If we display the teams and ppl without team can contact it'll be more convenient. We can also incorporate the tech stack feature that tues has for the teams.

**Comment by nikolayninov** [comment]
Alas, that's just a suggestion, don't take it at face value

**Comment by asynchroza** [comment]
> > > Regarding when should the registration form be closed, this issue still has to be discussed, but i'd suggest for example:
> > > let's say we have 12 teams cap
> > > 11 predefined teams
> > > 1 team out of ppl without a team
> > > Another option (the one i think is best for everyone) is not to allow ppl to register without a team but rather display the already registered ones and singletons can contact them on their own and ask to join, this way we can utilize the url functionality even better 🫡
> > > 
> > > Of course, in case someone decides to register alone as a team in case he finds more ppl and wants to save a spot, we can add smth like "if you don't have 4 ppl in your team 1 week prior to the hackathon, your team will be disqualified and your spot will be empty lol"
> > 
> > What do you think about my suggestion from the comment - automatically allocating teams for participants without teams?
> > Have a new team form up for each 6 non-team participants. 
> > 
> > For example: 
> > There are 6 regular teams.
> > 6 non-team participants have signed up. These 6 members fill up the capacity but do not exceed it. Therefore one team for non-team participants is enough. Total teams - 7
> > 
> > A new non-team participant tries to sign up. Now we have 7 non-team participants. A new team is being created because the count with the new participant will exceed 6 (max cap of team members). Therefore this new participant is being allocated to the new team. Total teams - 8
> > 
> > We can further extend this by splitting the non-team participants equally among the teams. Have the two non-team teams as 4 and 3 participants instead of 6 and 1. Nevertheless, I think this will increase the complexity quite a bit and we can do this manually on the day of the hackathon.
> > 
> 
> 
> I think this might create weirdly balanced teams, e.g. all designers, all coders, etc. (Iren's sister's team from last year is a good example of that) If we display the teams and ppl without team can contact them it'll be more convenient. We can also incorporate the tech stack feature that tues has for the teams.

Indeed, you're correct.

Unpopular opinion - let's make the hackathon about programming and not about the best presentations and drawings. Having designers sign up to a programming competition (hackathon) is plain dumb if you ask me. If we want to focus on having it more business oriented, let's rename it to something else.

Back on the topic, having the TUES logic implemented will be too much work and this team doesn't iterate fast enough to have it all done by March and be sure it's all working as expected.

**Comment by nikolayninov** [comment]
> > Regarding when should the registration form be closed, this issue still has to be discussed, but i'd suggest for example:
> > let's say we have 12 teams cap
> > 11 predefined teams
> > 1 team out of ppl without a team
> > Another option (the one i think is best for everyone) is not to allow ppl to register without a team but rather display the already registered ones and singletons can contact them on their own and ask to join, this way we can utilize the url functionality even better 🫡
> > 
> > Of course, in case someone decides to register alone as a team in case he finds more ppl and wants to save a spot, we can add smth like "if you don't have 4 ppl in your team 1 week prior to the hackathon, your team will be disqualified and your spot will be empty lol"
> 
> Now, I better grasp what you mean by saying "better utilize the url functionality". That's a cool idea I would like to explore but this will require the implementation of an approval functionality for team admins to accept members within the teams. Additionally, this way we depend too much on having people read our guide on how to sign up when we can have most of the stuff abstracted and just do it behind the scenes. We're not allowed to share any public info about the teams other than name and capacity (at least that's what I assume).

oof you got a point, i gueess, they can press on the team and post a request to join, ofc if the capacity allows for it. We can also ask the admin whether they r open to outsiders joining them and ask whether they want their email to be displayed or smth, thats a workaround. This way the admin can just send the url to the new participant or smth

**Comment by nikolayninov** [comment]
> > > What do you think about my suggestion from the comment - automatically allocating teams for participants without teams?
> > > Have a new team form up for each 6 non-team participants. 
> > > 
> > > For example: 
> > > There are 6 regular teams.
> > > 6 non-team participants have signed up. These 6 members fill up the capacity but do not exceed it. Therefore one team for non-team participants is enough. Total teams - 7
> > > 
> > > A new non-team participant tries to sign up. Now we have 7 non-team participants. A new team is being created because the count with the new participant will exceed 6 (max cap of team members). Therefore this new participant is being allocated to the new team. Total teams - 8
> > > 
> > > We can further extend this by splitting the non-team participants equally among the teams. Have the two non-team teams as 4 and 3 participants instead of 6 and 1. Nevertheless, I think this will increase the complexity quite a bit and we can do this manually on the day of the hackathon.
> > > 
> > 
> > 
> > I think this might create weirdly balanced teams, e.g. all designers, all coders, etc. (Iren's sister's team from last year is a good example of that) If we display the teams and ppl without team can contact them it'll be more convenient. We can also incorporate the tech stack feature that tues has for the teams.
> 
> Indeed, you're correct.
> 
> Unpopular opinion - let's make the hackathon about programming and not about the best presentations and drawings. Having designers sign up to a programming competition (hackathon) is plain dumb if you ask me. If we want to focus on having it more business oriented, let's rename it to something else.
> 
> Back on the topic, having the TUES logic implemented will be too much work and this team doesn't iterate fast enough to have it all done by March and be sure it's all working as expected.

The tues could be left in case we have time, it's not mandatory

**Comment by IvanObreshkov** [comment]
When we were discussing the logic with @Aleks1908 we also thought about the situation where someone could leak that link and random people to join the particular team. This could be prevented by implementing logic where for each new registered team member the admin of the team receives an email giving him the option to accept or reject that person. In my opinion, this will not be easy to implement, and we decided to leave it if there is time left. 

My other consideration is about the people without teams. The idea of @nikolayninov is interesting, but I don't believe that someone would accept a random person on their team. Also, the hassle of having to write to someone begging them to join their team is too much friction for the person who registers. I like the idea of, for example, having a maximum team capacity of 15 and leaving one or two spots for teams created out of the members without a team. For example, let's say that we have 12 people without a team. We could randomly or manually pick 6 people and put them in one team and the other 6 in the other. The problem here is that we would have to keep at least one spot for a team created out of random people. This means that if our max capacity of teams is 15 we have to close the registration for teams at 14, in order to have a spot for the team formed by people, who registered alone. But whether it should be one or two spots is unpredictable, because we don't know how many people without a team would register. Also the decision of the maximum number of teams and people we would accept, and whether we could exceed that number is not a decision I should take.

**Comment by asynchroza** [comment]
> When we were discussing the logic with @Aleks1908 and thought about the situation where someone could leak the invite link and random people might join the particular team. This could be prevented by implementing the logic mentioned above, where for each new registered team member the admin of the team receives an email giving them the option to accept or reject that person. In my opinion, this will not be easy to implement, and we decided to leave it if there is time left. 
> 
> 
> 
> My other consideration is about the people without teams. The idea of @nikolayninov is interesting, but I don't believe that someone would accept a random person on their team. Also, the hassle of having to write to someone begging them to join their team creates too much friction for the person who registers. I like the idea of, for example, having a maximum team capacity of 15 and leaving one or two spots for teams created out of the members without a team. For example, let's say that we have 12 people without a team. We could randomly or manually pick 6 people and put them in one team and the other 6 in the other. The problem is that we would have to keep at least one spot for a team created by random people. This means that if our max capacity of teams is 15 we have to close the registration for teams at 14, in order to have a spot for the team formed by people, who registered alone. But whether it should be one or two spots is unpredictable, because we don't know how many people without a team would register. Also the decision of the maximum number of teams and people we would accept, and whether we could exceed that number is not a decision I should take.

Okay. Since you're the lead here, I suggest that you reread my suggestion and build upon it. Both ideas are quite similar with the difference that mine will allocate the teams of people entering without a team upon registration. I can think of some other edge cases such as when the cap of teams is reached but the teams formed from non-team participants have free spots left, we should still allow for more non-team participants to sign up. Please, make sure to scribble down a good flowchart for this since a lot of frontend work will depend on that as well.

**Comment by IvanObreshkov** [comment]
@Aleks1908 we should finish this by 09/03/2023 (Sunday)

**Comment by asynchroza** [comment]
> @Aleks1908 we should finish this by 09/03/2023 (Sunday)

I'm willing to help you figure out stuff. Ping me when needed and we can work it out on Discord.

**Comment by IvanObreshkov** [comment]
@Aleks1908 @asynchroza I am here is the [link ](https://excalidraw.com/#room=a37ba3e1ae9461020241,hd1sv_rr2R5BAC35VcPGTA) to the excalidraw room. I am attaching a picture as well 
![Untitled-2023-09-03-1637](https://github.com/AUBGTheHUB/monolith/assets/38375079/34949c6a-0ffa-4549-85f0-b42a7291e912) Please leave feedback in the ticket or add changes to the workflow via Excalidraw.

**Comment by Aleks1908** [comment]
Today me and Ivan went though the workflow again and everything looks to be fine for now. So i will be closing this issue if no one has any improvement ideas.

**Comment by IvanObreshkov** [comment]
> Today me and Ivan went though the workflow again and everything looks to be fine for now. So i will be closing this issue if no one has any improvement ideas.

Pin the link to the scheme in Discord or messenger
