### ISSUE TITLE
[BUG] Fix analyzer service

### ISSUE THREAD

**Issue by IvanObreshkov** [AUBGTheHUB/monolith#551]
## Brief description:
![image](https://github.com/AUBGTheHUB/monolith/assets/38375079/f88c377c-b438-4666-a238-c023edeb5ec0)

## How to achieve it:
Figure it out

**Comment by asynchroza** [comment]
Check if bumping the version of nginx resolves this issue. I read somewhere that bumping to version 22 fixes similar errors.

**Comment by asynchroza** [comment]
> Check if bumping the version of nginx resolves this issue. I read somewhere that bumping to version 22 fixes similar errors.

Bumping the version actually fixes the SSL issue but there's another occurring problem.
I believe the IP is either not passed properly to the service or the actual value gets overwritten with the proxy's IP (the VM's IP). Therefore, this causes the service to update the analytics entry with a result matching the VM's location instead of the one of the requester.

https://serverfault.com/a/920060

**Comment by asynchroza** [comment]
If you provide an incorrect IP, the request will return your location.

```
x curl https://geolocation-db.com/json/something

{"country_code":"BG","country_name":"Bulgaria","city":"Berkovitsa Municipality","postal":"3500","latitude":43.2361,"longitude":23.1258,"IPv4":"178.254.212.169","state":"Oblast Montana"}%

```
