### ISSUE TITLE
[FEATURE] cron workflow for running certbot update on virtual machines

### ISSUE THREAD

**Issue by asynchroza** [AUBGTheHUB/monolith#557]
## Brief description:
Perform a certification update on the virtual machine every three months, during the early morning hours.

**Comment by IvanObreshkov** [comment]
> ## Brief description:
> 
> Perform a certification update on the virtual machine every three months, during the early morning hours.

## Brief description:
On both PROD and DEV machines, we have certbot installed. By default, certbot has its cronjob which renews the certificates twice a day every 24 hours, but the problem is that they are stored in the`/etc/letsencrypt/live/domain` folder as ` fullchain.pem` and `privkey.pem` filles. 

The cron job should run every 89 days (this is when the original cert in the `/data/certs` folder expires) and copy `fullchain.pem`, `privkey.pem`, and move them to `data/certs` folder with names `devenv.crt` and `devenv.key` respectively.

@asynchroza feedback on this solution is appreciated.

**Comment by asynchroza** [comment]
@IvanObreshkov okay, this sounds good. Could you check if certificates are loaded in memory when nginx is started up or they're loaded upon request? If it's the former, you will have to figure out how to restart containers when certificates are updated.

**Comment by IvanObreshkov** [comment]
> @IvanObreshkov okay, this sounds good. Could you check if certificates are loaded in memory when nginx is started up or they're loaded upon request? If it's the former, you will have to figure out how to restart containers when certificates are updated.

@asynchroza I believe they are loaded when nginx starts. Either way we have to rebuild the containers in order for us to update the certs.
